import Head from 'next/head'
import ClientSideComponent from '@/components/ClientSideComponent'

export default function ClientSide() {
  return (
    <>
      <Head>
        <title>Client side page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
       <ClientSideComponent/>
      </main>
    </>
  )
}
