import ServerSideComponent from '@/components/ServerSideComponent'
import Head from 'next/head'

export default function ServerSide() {
  return (
    <>
      <Head>
        <title>Server side page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <ServerSideComponent/>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  return {
    props: {               
      isDesktop: true
    }
  }
}
